//auth actions types
export const AUTH_USER_SIGNUP_PENDING = 'AUTH_USER_SIGNUP_PENDING';
export const AUTH_USER_SIGNUP_ERROR = 'AUTH_USER_SIGNUP_ERROR';
export const AUTH_USER_SIGNUP_SUCCESS = 'AUTH_USER_SIGNUP_SUCCESS';
export const AUTH_USER_SIGNUP_CLEAR = 'AUTH_USER_SIGNUP_CLEAR';
export const AUTH_USER_SIGNIN_PENDING = 'AUTH_USER_SIGNIN_PENDING';
export const AUTH_USER_SIGNIN_ERROR = 'AUTH_USER_SIGNIN_ERROR';
export const AUTH_USER_SIGNIN_SUCCESS = 'AUTH_USER_SIGNIN_SUCCESS';
export const AUTH_USER_SIGNIN_CLEAR = 'AUTH_USER_SIGNIN_CLEAR';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const BOILERS_PENDING = 'BOILERS_PENDING';
export const BOILERS_ERROR = 'BOILERS_ERROR';
export const BOILERS_CLEAR = 'BOILERS_CLEAR';
export const BOILERS_GETALL_SUCCESS = 'BOILERS_GETALL_SUCCESS';
export const BOILERS_BOILER_PENDING = 'BOILERS_BOILER_PENDING';
export const BOILERS_BOILER_ERROR = 'BOILERS_BOILER_ERROR';
export const BOILERS_BOILER_CLEAR = 'BOILERS_BOILER_CLEAR';
export const BOILERS_BOILER_GET_SUCCESS = 'BOILERS_BOILER_GET_SUCCESS';
export const BOILERS_BOILER_DELETE_SUCCESS = 'BOILERS_BOILER_DELETE_SUCCESS';
export const BOILERS_BOILER_ADD_SUCCESS = 'BOILERS_BOILER_ADD_SUCCESS';
export const BOILERS_BOILER_EDIT_SUCCESS = 'BOILERS_BOILER_EDIT_SUCCESS';

